INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('I-BAJ' ,24,31500, 0, 0,'GRADE I BAJ ');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IA-BAJ' ,24,31500, 40500, 0,'GRADE IA BAJ HELPER SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IB-BAJ' ,24,36000, 0, 0,'GRADE IB BAJ JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('I-YGY-BAJ' ,24,30000, 0, 0,'GRADE I-YGY BAJ GDG YOGYA');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('II-BAJ' ,24,88000, 0, 0,'GRADE II BAJ SCRT SMG');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIA-BAJ' ,24,34000, 45000, 0,'GRADE IIA BAJ DRV SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIB-BAJ' ,24,95000, 0, 0,'GRADE IIB BAJ SCRT JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIA-BAJ' ,24,28000, 0, 0,'GRADE IIIA BAJ COLT SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIA-JKT-BAJ' ,24,32000, 0, 0,'GRADE IIIA-JKT BAJ COLT JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIB-BAJ' ,24,38500, 40000, 0,'GRADE IIIB BAJ STAFF ADM SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIB-JKT-BAJ' ,24,44000, 45000, 0,'GRADE IIIB-JKT BAJ STAFF ADM JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIC-BAJ' ,24,35000, 40000, 0,'GRADE IIIC BAJ SE SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIC-JKT-BAJ' ,24,40000, 50000, 0,'GRADE IIIC-JKT BAJ SE JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IIIC-MKT-JKT-BAJ' ,24,60000, 70000, 0,'GRADE IIIC-MKT-JKT BAJ MKT JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('III-YGY-BAJ' ,24,40000, 0, 0,'GRADE III-YGY BAJ STAFF YGY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('III-SLS-YGY-BAJ' ,24,40000, 0, 13000,'GRADE III-SLS-YGY BAJ SLS YGY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVA-BAJ' ,24,40000, 50000, 0,'GRADE IVA BAJ SPV SLS SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVA-SLS-YGY-BAJ' ,24,50000, 0, 0,'GRADE IVA-SLS-YGY BAJ SPV SLS YGY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVA-JKT-BAJ' ,24,44000, 60000, 0,'GRADE IVA-JKT BAJ SPV SLS JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVA-STAFF-BAJ' ,24,64000, 70000, 0,'GRADE IVA-STAFF BAJ SPV KBAG SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVA-STAFF-JKT-BAJ' ,24,68000, 70000, 0,'GRADE IVA-STAFF-JKT BAJ SPV KBAG JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVB-BAJ' ,24,51000, 75000, 0,'GRADE IVB BAJ COM DEL SBY JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IV-BAJ' ,24,87000, 90000, 0,'GRADE IV BAJ KONS INT SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('IVC-BAJ' ,24,56000, 90000, 0,'GRADE IVC BAJ ASM JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('V-BAJ' ,24,93000, 100000, 0,'GRADE V BAJ MAN SMG SBY');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('V-JKT-BAJ' ,24,62000, 95000, 0,'GRADE V-JKT BAJ MAN MKT SLS COR JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('V-BD-JKT-BAJ' ,24,0, 0, 0,'GRADE V-BD-JKT BAJ MAN BD JKT');
INSERT INTO hrd_salary_grade(grade_code,company_id,grade_allowance1,grade_allowance2,grade_allowance3,note) VALUES ('GM' ,24,102000, 115000, 0,'GRADE VI BAJ GM');