<?php
include_once('../global/session.php');
include_once('global.php');
include_once('activity.php');
include_once('form_object.php');
include_once('../global/employee_function.php');
include_once('cls_annual_leave.php');
$db = new CdbClass;
$db->connect();
setAutoAlpha($db, '2015-11-01', '2015-11-30');
//Cek data kehadiran yang in dan out nya tidak ada dan tidak ada info di absence
function setAutoAlpha($db, $strDateFrom, $strDateThru)
{
    $strCurDate = $strDateFrom;
    while (dateCompare($strCurDate, $strDateThru) <= 0) {
        $strSQL = "SELECT id FROM hrd_employee WHERE active=1 AND
                    id NOT IN (SELECT id_employee FROM hrd_attendance WHERE attendance_date = '$strCurDate')
                    AND id NOT IN (SELECT id_employee FROM hrd_absence_detail WHERE absence_date = '$strCurDate')";
        $resDb = $db->execute($strSQL);
        while ($rowDb = $db->fetchrow($resDb)) {
            $intLastID = 0;
            $strIDEmployee = $rowDb['id'];
            $bolHoliday = true;
            $bolHoliday = isHoliday($strCurDate);
            if ($bolHoliday == false) {
                $strSQL2 = "INSERT INTO hrd_absence (id_employee, date_from, date_thru, absence_type_code, note, status) VALUES
                           ($strIDEmployee, '$strCurDate', '$strCurDate', 'A', 'alpha generated by system', 2)";
                $resDb2 = $db->execute($strSQL2);
                $strSQL3 = "SELECT max(id) as last_id FROM hrd_absence WHERE id_employee = " . $rowDb['id'] . " AND note = 'alpha generated by system' ";
                $resDb3 = $db->execute($strSQL3);
                while ($rowDb3 = $db->fetchrow($resDb3)) {
                    $intLastID = $rowDb3['last_id'];
                }
                $strSQL4 = "INSERT INTO hrd_absence_detail (id_absence, id_employee, absence_date, absence_type) VALUES
                            ($intLastID, $strIDEmployee, '$strCurDate', 'A')";
                $resDb4 = $db->execute($strSQL4);
            }
        }
        $strCurDate = getNextDate($strCurDate);
    }
}

echo "kambing";
?>
