<?php
// -- ENGLISH --
// daftar istilah-istilah yang dipakai dalam program
// diterjemahkan dalam bahasa Inggris


$helpDictionary = array
(
  "no help" => "Sorry, no help provided in this page",
  "master user" => <<<EOD
Please enter information about user
<ol>
  <li>Login Name
    <ul>
      <li>Name of user login</li>
      <li>This login name will be use when user log-in into the system.</li>
    </ul>
  </li>
  <li>Password
    <ul>
      <li>A key to protect a user from anyone who is unauthorized.</li>
      <li>Good password combination always contain alphabet, numeric, and symbol.<br />
          e.g : p@\$\$w0rd</li>
    </ul>
  </li>
</ol>
EOD,

  "change password" => <<<EOD
How to change your password
<ol>
  <li>Old password
    <ul>
      <li>Put your old password</li>
    </ul>
  </li>
  <li>New password
    <ul>
      <li>A new key to use as password.</li>
      <li>Good quality password always contain alphabet, numeric, and symbol.<br />
          e.g : p@\$\$w0rd</li>
    </ul>
  </li>
  <li>Re-enter new password
    <ul>
      <li>is a repetation of your new password.</li>
      <li>Use to check that your new password input is correct.</li>
    </ul>
  </li>
  <li>Click Save button to save your new password
  </li>
  <li>Click Cancel button to cancel and go back to previous page
  </li>
</ol>
EOD

);

?>