<?php
// -- ENGLISH --
// daftar HELP
// diterjemahkan dalam bahasa Indonesia

$helpDictionary = array
(
  "no help" => "Sorry, bantuan tidak tersedia untuk halaman ini",
  "master user" => <<<EOD
Masukkan informasi dari pengguna:
<ol>
  <li>Nama Login
    <ul>
      <li>Nama dari login pengguna</li>
      <li>Nama ini akan digunakan untuk masuk ke aplikasi/sistem.</li>
    </ul>
  </li>
  <li>Kata kunci
    <ul>
      <li>Adalah kunci untuk melindungi pengguna dari seseorang yang tidak berkepentingan.</li>
      <li>Kata kunci yang baik selalu mengandung huruf, angka, dan simbol.<br />
          contoh : p@\$\$w0rd</li>
    </ul>
  </li>
</ol>
EOD,

  "master group" => <<<EOD
  Help untuk grup
EOD,

  "change password" => <<<EOD
Petunjuk penggunaan mengubah kata kunci, Halaman ini berfungsi untuk mengubah kata kunci lama anda dengan kata kunci yang baru.
<ol>
  <li>Kata kunci lama
    <ul>
      <li>Adalah kata kunci anda yang lama</li>
    </ul>
  </li>
  <li>Kata kunci baru
    <ul>
      <li>Adalah kata kunci baru yang akan anda gunakan.</li>
      <li>Kata kunci yang baik selalu mengandung huruf, angka, dan simbol.<br />
          contoh : p@\$\$w0rd</li>
    </ul>
  </li>
  <li>Ulangi Kata kunci baru
    <ul>
      <li>Adalah pengulangan kata kunci baru yang akan anda gunakan.</li>
      <li>Hanya sebagai pengecek supaya kata kunci yang anda input tidak salah.</li>
    </ul>
  </li>
  <li>Klik tombol Simpan untuk menyimpan kata kunci baru anda
  </li>
  <li>Klik tombol Batal jika anda ingin membatalkan perubahan kata kunci
  </li>
</ol>
EOD,
  "master module" => <<<EOD
Masukkan nama module dari aplikasi
EOD
);

?>
